name: Build KDMapper

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.sln'
      - '**.cpp'
      - '**.h'
  pull_request:
    branches:
      - main
    paths:
      - '**.sln'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: '17.0'

      - name: Install Windows SDK
        run: |
          choco install -y windows-sdk-10.0
        shell: powershell

      - name: Install Windows Driver Kit
        run: |
          choco install -y windowsdriverkit10
        shell: powershell

      - name: Build KDMapper Solution
        run: |
          msbuild kdmapper.sln /p:Configuration=Release /p:Platform=x64 /m
        shell: cmd

      - name: Debug Output Directory Structure
        run: |
          dir /s /p
          if exist "kdmapper\bin\Release\kdmapper.exe" echo "Found kdmapper.exe in kdmapper\bin\Release"
          if exist "bin\Release\kdmapper.exe" echo "Found kdmapper.exe in bin\Release"
          if exist "Release\kdmapper.exe" echo "Found kdmapper.exe in Release"
        shell: cmd

      - name: Create Artifact Directory
        run: |
          mkdir -p artifacts
          if exist "kdmapper\bin\Release\kdmapper.exe" copy "kdmapper\bin\Release\kdmapper.exe" "artifacts\kdmapper.exe"
          if exist "bin\Release\kdmapper.exe" copy "bin\Release\kdmapper.exe" "artifacts\kdmapper.exe"
          if exist "Release\kdmapper.exe" copy "Release\kdmapper.exe" "artifacts\kdmapper.exe"
          dir artifacts
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kdmapper-release
          path: artifacts/*
          retention-days: 7
