name: Build KDMapper

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.sln'
      - '**.cpp'
      - '**.h'
  pull_request:
    branches:
      - master
    paths:
      - '**.sln'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: '17.0'

      - name: Install Windows SDK
        run: |
          choco install -y windows-sdk-10.0
        shell: powershell

      - name: Install Windows Driver Kit
        run: |
          choco install -y windowsdriverkit10
        shell: powershell

      - name: Build KDMapper Solution
        run: |
          msbuild kdmapper.sln /p:Configuration=Release /p:Platform=x64 /m
        shell: cmd

      - name: Search for EXE Files
        run: |
          echo "Searching for all .exe files in the repository..."
          dir "*.exe" /s /p
        shell: cmd

      - name: Create Artifact Directory
        run: |
          mkdir -p artifacts
          echo "Attempting to copy known possible locations for kdmapper.exe..."
          if exist "kdmapper\bin\Release\kdmapper.exe" copy "kdmapper\bin\Release\kdmapper.exe" "artifacts\kdmapper.exe"
          if exist "bin\Release\kdmapper.exe" copy "bin\Release\kdmapper.exe" "artifacts\kdmapper.exe"
          if exist "Release\kdmapper.exe" copy "Release\kdmapper.exe" "artifacts\kdmapper.exe"
          if exist "kdmapper\Release\kdmapper.exe" copy "kdmapper\Release\kdmapper.exe" "artifacts\kdmapper.exe"
          dir artifacts
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kdmapper-release
          path: artifacts/*
          retention-days: 7
          if-no-files-found: warn
